[package]
name = "project-01"
version = "0.1.0"
edition = "2024"
license = "GPL"
description = "PROJECT-01"
[dependencies]
actix-mqtt="*"
actix-mqtt-client="*"
actix-postgres="*"
actix-redis="*"
actix-redisactor="*"
actix-redis-client="*"
actix-session-sqlx-postgres="*"
actix-storage-redis="*"
actix-web="*"
actix-websockets="*"
actori-redis="*"
adafruit-qt-py-rp2040="*"
adafruit-trinkey-qt2040="*"
afl="*"
async-wasm="*"
axum="*"
axum-typed-websockets="*"
axum-wasm-macros="*"
axum-xml="*"
axum-xml-extract="*"
axum-xml-up="*"
axum-ycrdt-websocket="*"
burn="*"
burn-autodiff="*"
burn-compute="*"
burn-contracts="*"
burn-core="*"
burn-cuda="*"
burn-fusion="*"
burn-hip="*"
burn-import="*"
burn-ir="*"
burn-jit="*"
burn-ndarray="*"
burn-rocm="*"
burn-router="*"
burn-tensor="*"
burn-tensor-testgen="*"
burn-train="*"
burn-vision="*"
burn-wgpu="*"
cargo-qtest="*"
chrome-wasm-bindgen="*"
fastjson="*"
fastwebsockets="*"
flat-json="*"
garde="*"
garde_derive ="*"
geo-plot="*"
ggplot-derive="*"
ggplot-error="*"
gnuplot="*"
grpc="*"
grpc-build="*"
grpc-build-core="*"
grpc-build-derive="*"
grpc_client="*"
grpc-compiler="*"
grpc-ease="*"
grpc_etcd="*"
grpc_gateway="*"
grpc_health_probe="*"
grpc-proxy="*"
grpc-rust="*"
grpc_schemas_example="*"
grpc-status="*"
grpc-web-client="*"
hydra-websockets="*"
json="*"
json2excel="*"
kafka="*"
kafka-broker="*"
kafka-clients="*"
libxml="*"
log="*"
matplotlib="*"
matplotrust="*"
mockall="*"
mqtt="*"
mqtt5="*"
mqtt5bytes="*"
mqtt5-server="*"
mysql-connector="*"
mysql-connector-macros="*"
next-web-websocket="*"
numpy="*"
pandas="*"
pandas_rs="*"
plotly="*"
plotly_derive="*"
plot-rs="*"
plotrs="*"
plotsweep="*"
plotting="*"
plotty="*"
plotxy="*"
postgres="*"
postgresql="*"
qtbridge="*"
qtbridges="*"
qt-build-utils="*"
qt-cb="*"
qt_charts="*"
qt_core="*"
qt_core_custom_events="*"
qtest="*"
qt_macros="*"
redis="*"
redis_connector="*"
redisgraphio="*"
redis-grpc="*"
regex ="*"
rocket="*"
rstorch="*"
rust-numpy="*"
rustorch="*"
rust-plotter="*"
rust-redis="*"
rust-redis-imitate="*"
rust_wasm_websocket="*"
rust-xmlrpc="*"
rust-xmlsec="*"
serde ="*"
serde-redis="*"
serde_xml="*"
serde-xml-any="*"
serde_xmlrpc="*"
serde-xml-rust="*"
servo-websocket="*"
sessions-redis="*"
simple-plot="*"
simple-websockets="*"
subplot="*"
subplot-bin="*"
subplot-build="*"
subplotlib="*"
subplotlib-derive="*"
syslog="*"
systemd_socket="*"
test-case="*"
time="*"
tokio="*"
tokio-dbus-xml="*"
tokio-mqtt="*"
tokio-postgres="*"
tokio-postgres-extractor="*"
tokio-postgres-extractor-macros="*"
tokio-postgres-fork="*"
tokio-postgres-generic-rustls="*"
tokio-postgres-macros="*"
tokio-postgres-migration="*"
tokio-postgres-rustls="*"
tokio-postgres-rustls-improved="*"
tokio-postgres-tls="*"
tokio-postgres-utils="*"
tokio-postgres_wasi="*"
tokio-shared-udp-socket="*"
tokio_socket2="*"
tokio-socketcan="*"
tokio-socketcan-bcm="*"
tokio-socketcan-isotp="*"
tokio-websocket="*"
tokio-websocket-client="*"
tokio-websockets="*"
tokio_websocket_server="*"
tokio_with_wasm="*"
tokio_with_wasm_proc="*"
tonic="*"
tonic-web-wasm-client="*"
torch="*"
torch-rs="*"
torch-web="*"
wasm4="*"
wasm-bindgen="*"
wasm-bindgen-anyref-xform="*"
wasm-bindgen-backend="*"
wasm_bindgen_cfg="*"
wasm-bindgen-cli="*"
wasm-bindgen-console-logger="*"
wasm-bindgen-derive="*"
wasm-bindgen-derive-macro="*"
wasm-bindgen-downcast="*"
wasm-bindgen-downcast-macros="*"
wasm_bindgen_duck_type="*"
wasm_bindgen_duck_type_macro_impl="*"
wasm-bindgen-externref-xform="*"
wasm-bindgen-file-reader="*"
wasm-bindgen-gc="*"
wasm_bindgen_helper="*"
wasm_bindgen_helper_macros="*"
wasm-bindgen-macro="*"
wasm-bindgen-multi-value-xform="*"
wasm-bindgen-rayon="*"
wasm-bindgen-shared="*"
wasm-bindgen-spawn="*"
wasm-bindgen-struct="*"
wasm-bindgen-test="*"
wasm-bindgen-test-crate-a="*"
wasm-bindgen-test-crate-b="*"
wasm-bindgen-test-macro="*"
wasm-bindgen-threads-xform="*"
wasm-bindgen-utils="*"
wasm-bindgen-utils-macros="*"
wasm-bindgen-wasm-conventions="*"
wasm-bindgen-wasm-interpreter="*"
websocket="*"
websocket-async-io="*"
websocket-base="*"
websocket-codec="*"
websocket_handshake="*"
websocket-lite="*"
websocket-rs="*"
websocket-sans-io="*"
websocket-stream="*"
websocket_toolkit="*"
websocket-transport="*"
websocket-util="*"
websocket-web="*"
websock-wasm="*"
xml2json="*"
xml2json-rs="*"
xmlparser="*"
