[package]
name = "project-01"
version = "0.1.1"
edition = "2024"
publish = ["cargo-prod","cargo-test"]

[dependencies]
tonic = "*"
prost = "0.14"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
tonic-prost-build = "*"

