[package]
name = "project-01"
version = "0.1.2"
edition = "2024"
publish = ["cargo-prod","cargo-test"]

[dependencies]
tonic = "*"
prost = "0.14"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tonic-prost="*"

[build-dependencies]
tonic-prost-build = "*"

